[functions.buy-item]
enabled = true
verify_jwt = false

[functions.complete-quest]
enabled = true
verify_jwt = false

[functions.daily-cron]
enabled = true
verify_jwt = false

[functions.create-custom-quest]
enabled = true
verify_jwt = false

[functions.generate-quests]
enabled = true
verify_jwt = false

[functions.generate-rewards]
enabled = true
verify_jwt = false

[functions.generate-shop]
enabled = true
verify_jwt = false

[functions.regenerate-quests]
enabled = true
verify_jwt = false

[functions.skip-quest]
enabled = true
verify_jwt = false

[functions.settle-daily]
enabled = true
verify_jwt = false

[functions.use-inventory-item]
enabled = true
verify_jwt = false
